<?php

return [
    'label' => 'ECharts',
    'icon' => 'fa fa-bar-chart',
    'description' => 'Bar, Line, Area, Pie, Donut und Scatter aus manuellen Daten oder YForm.',
    'version' => '1.0.0',
    'category' => 'content',
    'settings_modal' => [
        'label' => 'Einstellungen & Globals',
        'icon' => 'fa-sliders',
        'fieldsets' => [
            [
                'label' => 'Farben',
                'fields' => ['global_color'],
            ],
            [
                'label' => 'Anzeige',
                'fields' => ['show_legend', 'show_tooltip', 'show_labels', 'show_pie_inside_values', 'show_grid', 'show_export_buttons', 'export_svg', 'export_pdf'],
            ],
            [
                'label' => 'Erweitert',
                'fields' => ['chart_options_json'],
            ],
        ],
    ],
    'fields' => [
        'headline' => [
            'type' => 'text',
            'label' => 'Überschrift',
        ],
        'chart_title' => [
            'type' => 'text',
            'label' => 'Chart-Titel',
        ],
        'chart_type' => [
            'type' => 'choice',
            'label' => 'Chart-Typ',
            'choices' => [
                'bar' => 'Balken',
                'line' => 'Linie',
                'area' => 'Fläche',
                'pie' => 'Pie',
                'donut' => 'Donut',
                'gauge_simple' => 'Gauge (Simple)',
                'gauge_ring' => 'Gauge (Ring)',
                'scatter' => 'Scatter',
            ],
            'default' => 'bar',
        ],
        'height' => [
            'type' => 'text',
            'label' => 'Höhe',
            'default' => '380',
            'notice' => 'Zahl in Pixel oder CSS-Wert wie 28rem.',
        ],
        'source_type' => [
            'type' => 'choice',
            'label' => 'Datenquelle',
            'choices' => [
                'manual' => 'Manuelle Werte',
                'csv' => 'CSV',
                'yform' => 'YForm-Tabelle',
            ],
            'default' => 'manual',
        ],
        'manual_items' => [
            'type' => 'repeater',
            'label' => 'Manuelle Datenpunkte',
            'add_label' => '+ Datenpunkt hinzufügen',
            'view' => 'list',
            'visible_if' => ['source_type' => ['manual']],
            'item_modal' => [
                'label' => 'Optionen',
                'icon' => 'fa-sliders',
                'modal_size' => 'xl',
                'trigger_after' => 'value',
                'fields' => ['tooltip', 'has_color', 'color', 'has_link', 'link'],
            ],
            'fields' => [
                'label' => [
                    'type' => 'text',
                    'label' => 'Label',
                    'required' => true,
                    'col' => 8,
                ],
                'value' => [
                    'type' => 'text',
                    'label' => 'Wert',
                    'required' => true,
                    'col' => 4,
                ],
                'tooltip' => [
                    'type' => 'text',
                    'label' => 'Tooltip (optional)',
                    'col' => 12,
                ],
                'has_color' => [
                    'type' => 'checkbox',
                    'label' => 'Farbe aktivieren',
                    'default' => 0,
                    'col' => 6,
                ],
                'color' => [
                    'type' => 'color',
                    'label' => 'Farbwert',
                    'col' => 6,
                    'visible_if' => ['has_color' => ['1']],
                ],
                'has_link' => [
                    'type' => 'checkbox',
                    'label' => 'Link aktivieren',
                    'default' => 0,
                    'col' => 6,
                ],
                'link' => [
                    'type' => 'smart_link',
                    'label' => 'Link (optional)',
                    'notice' => 'Smart Link: intern, extern, Media, Mail, Tel',
                    'col' => 12,
                    'visible_if' => ['has_link' => ['1']],
                ],
            ],
        ],
        'global_color' => [
            'type' => 'color',
            'label' => 'Globale Standardfarbe (optional)',
            'notice' => 'Wird verwendet, wenn ein Punkt keine eigene Farbe hat.',
        ],
        'csv_data' => [
            'type' => 'textarea',
            'label' => 'CSV-Daten',
            'rows' => 8,
            'notice' => 'Mit Header (empfohlen): label,value,link,tooltip,color,has_link,has_color',
            'default' => "label,value,tooltip\nQ1,120,Start\nQ2,180,Wachstum",
            'visible_if' => ['source_type' => ['csv']],
        ],
        'csv_delimiter' => [
            'type' => 'choice',
            'label' => 'CSV-Trennzeichen',
            'choices' => [
                ',' => 'Komma (,)',
                ';' => 'Semikolon (;)',
                'tab' => 'Tab',
            ],
            'default' => ',',
            'visible_if' => ['source_type' => ['csv']],
        ],
        'csv_has_header' => [
            'type' => 'checkbox',
            'label' => 'Erste Zeile ist Header',
            'default' => 1,
            'visible_if' => ['source_type' => ['csv']],
        ],
        'show_legend' => [
            'type' => 'checkbox',
            'label' => 'Legende anzeigen',
            'default' => 1,
        ],
        'show_tooltip' => [
            'type' => 'checkbox',
            'label' => 'Tooltip anzeigen',
            'default' => 1,
        ],
        'show_labels' => [
            'type' => 'checkbox',
            'label' => 'Werte-Labels anzeigen',
            'notice' => 'Zeigt Werte direkt am Datenpunkt/Balken an.',
        ],
        'show_pie_inside_values' => [
            'type' => 'checkbox',
            'label' => 'Pie/Donut-Werte in der Torte anzeigen',
            'notice' => 'Zeigt Werte innerhalb von Pie/Donut-Segmenten, wenn genug Platz vorhanden ist.',
            'default' => 0,
            'visible_if' => ['chart_type' => ['pie', 'donut']],
        ],
        'show_grid' => [
            'type' => 'checkbox',
            'label' => 'Grid-Linien anzeigen',
            'default' => 1,
        ],
        'show_export_buttons' => [
            'type' => 'checkbox',
            'label' => 'Export-Buttons anzeigen',
            'notice' => 'Zeigt Export-Buttons direkt in der Grafik (Toolbox).',
            'default' => 0,
        ],
        'export_svg' => [
            'type' => 'checkbox',
            'label' => 'SVG-Export bevorzugen',
            'notice' => 'Aktiviert SVG-Renderer für schärfere Vektor-Exporte.',
            'default' => 0,
            'visible_if' => ['show_export_buttons' => ['1']],
        ],
        'export_pdf' => [
            'type' => 'checkbox',
            'label' => 'PDF-Export anzeigen',
            'notice' => 'Öffnet einen druckfertigen Dialog (als PDF speicherbar).',
            'default' => 0,
            'visible_if' => ['show_export_buttons' => ['1']],
        ],
        'yform_table' => [
            'type' => 'text',
            'label' => 'YForm-Tabelle',
            'notice' => 'Beispiel: rex_sales',
            'visible_if' => ['source_type' => ['yform']],
        ],
        'yform_label_field' => [
            'type' => 'text',
            'label' => 'YForm Label-Feld',
            'default' => 'name',
            'visible_if' => ['source_type' => ['yform']],
        ],
        'yform_value_field' => [
            'type' => 'text',
            'label' => 'YForm Value-Feld',
            'default' => 'value',
            'visible_if' => ['source_type' => ['yform']],
        ],
        'yform_limit' => [
            'type' => 'text',
            'label' => 'YForm Limit',
            'default' => '12',
            'visible_if' => ['source_type' => ['yform']],
        ],
        'chart_options_json' => [
            'type' => 'echarts_option',
            'label' => 'Chart-Konfiguration (JSON-Override)',
            'notice' => 'Optional: vollständige ECharts-Optionen. Wenn gesetzt, überschreibt es Presets.',
        ],
    ],
];
